name: Package example

on:
  push:
    branches:
      - main

jobs:
  publish_package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone repo
        uses: "actions/checkout@v4"

      - name: Configure .npmrc
        uses: "actions/setup-node@v4"
        with:
          node-version: '22.x'

