name: Package example

on:
  push:
    branches:
      - main

jobs:
  publish_package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Extract version from CHANGELOG.md
        id: extract_version
        run: |
          version=$(grep -Eo '## \[[0-9]+\.[0-9]+\.[0-9]+\]' CHANGELOG.md | head -1 | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=$version" >> "$GITHUB_ENV"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Update package.json version
        run: |
          jq --arg v "${{ steps.extract_version.outputs.version }}" '.version=$v' package.json > tmp.json && mv tmp.json package.json

      - name: Configure .npmrc
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ricardojonathanromero'

      - name: Install dependencies
        run: npm ci

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

